services:
  - type: web
    name: quantum-ai
    runtime: python
    repo: https://github.com/mindtechindustriesai-alt/quantum-ai
    plan: free
    branch: main
    buildCommand: pip install --no-cache-dir --upgrade pip setuptools wheel && pip install --no-cache-dir -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: CHSH_S
        value: 2.76
      - key: QUANTUM_CORRELATION
        value: 0.984
      - key: IBM_JOB_ID
        value: d8uhvl4bp3hs738628cg
      - key: PATENT_NUMBER
        value: SA 2026/05142
